package linux

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestParseDnfModuleFile(t *testing.T) {
	contents := `
# generated by dnf
[nodejs]
stream=18
version=8060020220315191626
context=9edba152
state=installed

[postgresql]
name=postgresql
stream=13
state=enabled

[missing-stream]
state=enabled
`

	assert.Equal(t, []InstalledModule{
		{
			Name:    "nodejs",
			Stream:  "18",
			Version: "8060020220315191626",
			Context: "9edba152",
			State:   "installed",
		},
		{
			Name:   "postgresql",
			Stream: "13",
			State:  "enabled",
		},
	}, parseDnfModuleFile(contents))
}
